const colors = {
  light: {
    text: "#1E2A3B",
    tint: "#1F4E79",
    background: "#F8FAFC",
    foreground: "#1E2A3B",
    card: "#FFFFFF",
    cardForeground: "#1E2A3B",
    primary: "#1F4E79",
    primaryForeground: "#FAFEFF",
    secondary: "#EDF2F7",
    secondaryForeground: "#2D3748",
    muted: "#F0F4F8",
    mutedForeground: "#6B7A8D",
    accent: "#C55A11",
    accentForeground: "#FFFFFF",
    destructive: "#993C1D",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8EF",
    input: "#E2E8EF",
    success: "#1D9E75",
    successForeground: "#FFFFFF",
    warning: "#BA7517",
    warningForeground: "#FFFFFF",
    danger: "#993C1D",
    dangerForeground: "#FFFFFF",
  },
  dark: {
    text: "#F5F8FC",
    tint: "#3D72B4",
    background: "#151D2E",
    foreground: "#F5F8FC",
    card: "#1E2A3E",
    cardForeground: "#F5F8FC",
    primary: "#3D72B4",
    primaryForeground: "#FFFFFF",
    secondary: "#243047",
    secondaryForeground: "#E8EEF5",
    muted: "#243047",
    mutedForeground: "#8FA0B0",
    accent: "#C55A11",
    accentForeground: "#FFFFFF",
    destructive: "#B84D28",
    destructiveForeground: "#FFFFFF",
    border: "#243047",
    input: "#243047",
    success: "#1D9E75",
    successForeground: "#FFFFFF",
    warning: "#BA7517",
    warningForeground: "#FFFFFF",
    danger: "#B84D28",
    dangerForeground: "#FFFFFF",
  },
  radius: 8,
};

export default colors;
