/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PscRouteImport } from './routes/psc'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OrgRouteImport } from './routes/org'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ConsultantRouteImport } from './routes/consultant'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as ContractorTendersRouteImport } from './routes/contractor/tenders'
import { Route as ContractorProjectsRouteImport } from './routes/contractor/projects'
import { Route as ContractorProfileRouteImport } from './routes/contractor/profile'
import { Route as ContractorPaymentsRouteImport } from './routes/contractor/payments'
import { Route as ContractorBidsRouteImport } from './routes/contractor/bids'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ClientTendersRouteImport } from './routes/client/tenders'
import { Route as ClientProjectsRouteImport } from './routes/client/projects'
import { Route as ClientPaymentsRouteImport } from './routes/client/payments'
import { Route as ClientGate2RouteImport } from './routes/client/gate2'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as AuditorTrailRouteImport } from './routes/auditor/trail'
import { Route as AuditorFlagsRouteImport } from './routes/auditor/flags'
import { Route as AuditorIrregularitiesRouteImport } from './routes/auditor/irregularities'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as IndexRouteImport } from './routes/index'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders', path: '/tenders', getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier', path: '/supplier', getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports', path: '/reports', getParentRoute: () => rootRouteImport,
} as any)
const PscRoute = PscRouteImport.update({
  id: '/psc', path: '/psc', getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects', path: '/projects', getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile', path: '/profile', getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional', path: '/professional', getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments', path: '/payments', getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org', path: '/org', getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing', path: '/landing', getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation', path: '/evaluation', getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo', path: '/demo', getParentRoute: () => rootRouteImport,
} as any)
const ConsultantRoute = ConsultantRouteImport.update({
  id: '/consultant', path: '/consultant', getParentRoute: () => rootRouteImport,
} as any)
const ContractorRoute = ContractorRouteImport.update({
  id: '/contractor', path: '/contractor', getParentRoute: () => rootRouteImport,
} as any)
const ContractorTendersRoute = ContractorTendersRouteImport.update({
  id: '/contractor/tenders', path: '/contractor/tenders', getParentRoute: () => rootRouteImport,
} as any)
const ContractorProjectsRoute = ContractorProjectsRouteImport.update({
  id: '/contractor/projects', path: '/contractor/projects', getParentRoute: () => rootRouteImport,
} as any)
const ContractorProfileRoute = ContractorProfileRouteImport.update({
  id: '/contractor/profile', path: '/contractor/profile', getParentRoute: () => rootRouteImport,
} as any)
const ContractorPaymentsRoute = ContractorPaymentsRouteImport.update({
  id: '/contractor/payments', path: '/contractor/payments', getParentRoute: () => rootRouteImport,
} as any)
const ContractorBidsRoute = ContractorBidsRouteImport.update({
  id: '/contractor/bids', path: '/contractor/bids', getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance', path: '/compliance', getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client', path: '/client', getParentRoute: () => rootRouteImport,
} as any)
const ClientTendersRoute = ClientTendersRouteImport.update({
  id: '/client/tenders', path: '/client/tenders', getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/client/projects', path: '/client/projects', getParentRoute: () => rootRouteImport,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/client/payments', path: '/client/payments', getParentRoute: () => rootRouteImport,
} as any)
const ClientGate2Route = ClientGate2RouteImport.update({
  id: '/client/gate2', path: '/client/gate2', getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids', path: '/bids', getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor', path: '/auditor', getParentRoute: () => rootRouteImport,
} as any)
const AuditorTrailRoute = AuditorTrailRouteImport.update({
  id: '/auditor/trail', path: '/auditor/trail', getParentRoute: () => rootRouteImport,
} as any)
const AuditorFlagsRoute = AuditorFlagsRouteImport.update({
  id: '/auditor/flags', path: '/auditor/flags', getParentRoute: () => rootRouteImport,
} as any)
const AuditorIrregularitiesRoute = AuditorIrregularitiesRouteImport.update({
  id: '/auditor/irregularities', path: '/auditor/irregularities', getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup', path: '/auth/signup', getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login', path: '/auth/login', getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auditor': typeof AuditorRoute
  '/auditor/flags': typeof AuditorFlagsRoute
  '/auditor/irregularities': typeof AuditorIrregularitiesRoute
  '/auditor/trail': typeof AuditorTrailRoute
  '/bids': typeof BidsRoute
  '/client': typeof ClientRoute
  '/client/gate2': typeof ClientGate2Route
  '/client/payments': typeof ClientPaymentsRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/tenders': typeof ClientTendersRoute
  '/compliance': typeof ComplianceRoute
  '/consultant': typeof ConsultantRoute
  '/contractor': typeof ContractorRoute
  '/contractor/bids': typeof ContractorBidsRoute
  '/contractor/payments': typeof ContractorPaymentsRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/projects': typeof ContractorProjectsRoute
  '/contractor/tenders': typeof ContractorTendersRoute
  '/demo': typeof DemoRoute
  '/evaluation': typeof EvaluationRoute
  '/landing': typeof LandingRoute
  '/org': typeof OrgRoute
  '/payments': typeof PaymentsRoute
  '/professional': typeof ProfessionalRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/psc': typeof PscRoute
  '/reports': typeof ReportsRoute
  '/supplier': typeof SupplierRoute
  '/tenders': typeof TendersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auditor': typeof AuditorRoute
  '/auditor/flags': typeof AuditorFlagsRoute
  '/auditor/irregularities': typeof AuditorIrregularitiesRoute
  '/auditor/trail': typeof AuditorTrailRoute
  '/bids': typeof BidsRoute
  '/client': typeof ClientRoute
  '/client/gate2': typeof ClientGate2Route
  '/client/payments': typeof ClientPaymentsRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/tenders': typeof ClientTendersRoute
  '/compliance': typeof ComplianceRoute
  '/consultant': typeof ConsultantRoute
  '/contractor': typeof ContractorRoute
  '/contractor/bids': typeof ContractorBidsRoute
  '/contractor/payments': typeof ContractorPaymentsRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/projects': typeof ContractorProjectsRoute
  '/contractor/tenders': typeof ContractorTendersRoute
  '/demo': typeof DemoRoute
  '/evaluation': typeof EvaluationRoute
  '/landing': typeof LandingRoute
  '/org': typeof OrgRoute
  '/payments': typeof PaymentsRoute
  '/professional': typeof ProfessionalRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/psc': typeof PscRoute
  '/reports': typeof ReportsRoute
  '/supplier': typeof SupplierRoute
  '/tenders': typeof TendersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auditor': typeof AuditorRoute
  '/auditor/flags': typeof AuditorFlagsRoute
  '/auditor/irregularities': typeof AuditorIrregularitiesRoute
  '/auditor/trail': typeof AuditorTrailRoute
  '/bids': typeof BidsRoute
  '/client': typeof ClientRoute
  '/client/gate2': typeof ClientGate2Route
  '/client/payments': typeof ClientPaymentsRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/tenders': typeof ClientTendersRoute
  '/compliance': typeof ComplianceRoute
  '/consultant': typeof ConsultantRoute
  '/contractor': typeof ContractorRoute
  '/contractor/bids': typeof ContractorBidsRoute
  '/contractor/payments': typeof ContractorPaymentsRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/projects': typeof ContractorProjectsRoute
  '/contractor/tenders': typeof ContractorTendersRoute
  '/demo': typeof DemoRoute
  '/evaluation': typeof EvaluationRoute
  '/landing': typeof LandingRoute
  '/org': typeof OrgRoute
  '/payments': typeof PaymentsRoute
  '/professional': typeof ProfessionalRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/psc': typeof PscRoute
  '/reports': typeof ReportsRoute
  '/supplier': typeof SupplierRoute
  '/tenders': typeof TendersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/auditor'
    | '/auditor/flags'
    | '/auditor/irregularities'
    | '/auditor/trail'
    | '/bids'
    | '/client'
    | '/client/gate2'
    | '/client/payments'
    | '/client/projects'
    | '/client/tenders'
    | '/compliance'
    | '/consultant'
    | '/contractor'
    | '/contractor/bids'
    | '/contractor/payments'
    | '/contractor/profile'
    | '/contractor/projects'
    | '/contractor/tenders'
    | '/demo'
    | '/evaluation'
    | '/landing'
    | '/org'
    | '/payments'
    | '/professional'
    | '/profile'
    | '/projects'
    | '/psc'
    | '/reports'
    | '/supplier'
    | '/tenders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/auditor'
    | '/auditor/flags'
    | '/auditor/irregularities'
    | '/auditor/trail'
    | '/bids'
    | '/client'
    | '/client/gate2'
    | '/client/payments'
    | '/client/projects'
    | '/client/tenders'
    | '/compliance'
    | '/consultant'
    | '/contractor'
    | '/contractor/bids'
    | '/contractor/payments'
    | '/contractor/profile'
    | '/contractor/projects'
    | '/contractor/tenders'
    | '/demo'
    | '/evaluation'
    | '/landing'
    | '/org'
    | '/payments'
    | '/professional'
    | '/profile'
    | '/projects'
    | '/psc'
    | '/reports'
    | '/supplier'
    | '/tenders'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/auditor'
    | '/auditor/flags'
    | '/auditor/irregularities'
    | '/auditor/trail'
    | '/bids'
    | '/client'
    | '/client/gate2'
    | '/client/payments'
    | '/client/projects'
    | '/client/tenders'
    | '/compliance'
    | '/consultant'
    | '/contractor'
    | '/contractor/bids'
    | '/contractor/payments'
    | '/contractor/profile'
    | '/contractor/projects'
    | '/contractor/tenders'
    | '/demo'
    | '/evaluation'
    | '/landing'
    | '/org'
    | '/payments'
    | '/professional'
    | '/profile'
    | '/projects'
    | '/psc'
    | '/reports'
    | '/supplier'
    | '/tenders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuditorRoute: typeof AuditorRoute
  AuditorFlagsRoute: typeof AuditorFlagsRoute
  AuditorIrregularitiesRoute: typeof AuditorIrregularitiesRoute
  AuditorTrailRoute: typeof AuditorTrailRoute
  BidsRoute: typeof BidsRoute
  ClientRoute: typeof ClientRoute
  ClientGate2Route: typeof ClientGate2Route
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientProjectsRoute: typeof ClientProjectsRoute
  ClientTendersRoute: typeof ClientTendersRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsultantRoute: typeof ConsultantRoute
  ContractorRoute: typeof ContractorRoute
  ContractorBidsRoute: typeof ContractorBidsRoute
  ContractorPaymentsRoute: typeof ContractorPaymentsRoute
  ContractorProfileRoute: typeof ContractorProfileRoute
  ContractorProjectsRoute: typeof ContractorProjectsRoute
  ContractorTendersRoute: typeof ContractorTendersRoute
  DemoRoute: typeof DemoRoute
  EvaluationRoute: typeof EvaluationRoute
  LandingRoute: typeof LandingRoute
  OrgRoute: typeof OrgRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfessionalRoute: typeof ProfessionalRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  PscRoute: typeof PscRoute
  ReportsRoute: typeof ReportsRoute
  SupplierRoute: typeof SupplierRoute
  TendersRoute: typeof TendersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': { id: '/tenders'; path: '/tenders'; fullPath: '/tenders'; preLoaderRoute: typeof TendersRouteImport; parentRoute: typeof rootRouteImport }
    '/supplier': { id: '/supplier'; path: '/supplier'; fullPath: '/supplier'; preLoaderRoute: typeof SupplierRouteImport; parentRoute: typeof rootRouteImport }
    '/reports': { id: '/reports'; path: '/reports'; fullPath: '/reports'; preLoaderRoute: typeof ReportsRouteImport; parentRoute: typeof rootRouteImport }
    '/psc': { id: '/psc'; path: '/psc'; fullPath: '/psc'; preLoaderRoute: typeof PscRouteImport; parentRoute: typeof rootRouteImport }
    '/projects': { id: '/projects'; path: '/projects'; fullPath: '/projects'; preLoaderRoute: typeof ProjectsRouteImport; parentRoute: typeof rootRouteImport }
    '/profile': { id: '/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/professional': { id: '/professional'; path: '/professional'; fullPath: '/professional'; preLoaderRoute: typeof ProfessionalRouteImport; parentRoute: typeof rootRouteImport }
    '/payments': { id: '/payments'; path: '/payments'; fullPath: '/payments'; preLoaderRoute: typeof PaymentsRouteImport; parentRoute: typeof rootRouteImport }
    '/org': { id: '/org'; path: '/org'; fullPath: '/org'; preLoaderRoute: typeof OrgRouteImport; parentRoute: typeof rootRouteImport }
    '/landing': { id: '/landing'; path: '/landing'; fullPath: '/landing'; preLoaderRoute: typeof LandingRouteImport; parentRoute: typeof rootRouteImport }
    '/evaluation': { id: '/evaluation'; path: '/evaluation'; fullPath: '/evaluation'; preLoaderRoute: typeof EvaluationRouteImport; parentRoute: typeof rootRouteImport }
    '/demo': { id: '/demo'; path: '/demo'; fullPath: '/demo'; preLoaderRoute: typeof DemoRouteImport; parentRoute: typeof rootRouteImport }
    '/consultant': { id: '/consultant'; path: '/consultant'; fullPath: '/consultant'; preLoaderRoute: typeof ConsultantRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor': { id: '/contractor'; path: '/contractor'; fullPath: '/contractor'; preLoaderRoute: typeof ContractorRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor/tenders': { id: '/contractor/tenders'; path: '/contractor/tenders'; fullPath: '/contractor/tenders'; preLoaderRoute: typeof ContractorTendersRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor/projects': { id: '/contractor/projects'; path: '/contractor/projects'; fullPath: '/contractor/projects'; preLoaderRoute: typeof ContractorProjectsRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor/profile': { id: '/contractor/profile'; path: '/contractor/profile'; fullPath: '/contractor/profile'; preLoaderRoute: typeof ContractorProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor/payments': { id: '/contractor/payments'; path: '/contractor/payments'; fullPath: '/contractor/payments'; preLoaderRoute: typeof ContractorPaymentsRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor/bids': { id: '/contractor/bids'; path: '/contractor/bids'; fullPath: '/contractor/bids'; preLoaderRoute: typeof ContractorBidsRouteImport; parentRoute: typeof rootRouteImport }
    '/compliance': { id: '/compliance'; path: '/compliance'; fullPath: '/compliance'; preLoaderRoute: typeof ComplianceRouteImport; parentRoute: typeof rootRouteImport }
    '/client': { id: '/client'; path: '/client'; fullPath: '/client'; preLoaderRoute: typeof ClientRouteImport; parentRoute: typeof rootRouteImport }
    '/client/tenders': { id: '/client/tenders'; path: '/client/tenders'; fullPath: '/client/tenders'; preLoaderRoute: typeof ClientTendersRouteImport; parentRoute: typeof rootRouteImport }
    '/client/projects': { id: '/client/projects'; path: '/client/projects'; fullPath: '/client/projects'; preLoaderRoute: typeof ClientProjectsRouteImport; parentRoute: typeof rootRouteImport }
    '/client/payments': { id: '/client/payments'; path: '/client/payments'; fullPath: '/client/payments'; preLoaderRoute: typeof ClientPaymentsRouteImport; parentRoute: typeof rootRouteImport }
    '/client/gate2': { id: '/client/gate2'; path: '/client/gate2'; fullPath: '/client/gate2'; preLoaderRoute: typeof ClientGate2RouteImport; parentRoute: typeof rootRouteImport }
    '/bids': { id: '/bids'; path: '/bids'; fullPath: '/bids'; preLoaderRoute: typeof BidsRouteImport; parentRoute: typeof rootRouteImport }
    '/auditor': { id: '/auditor'; path: '/auditor'; fullPath: '/auditor'; preLoaderRoute: typeof AuditorRouteImport; parentRoute: typeof rootRouteImport }
    '/auditor/trail': { id: '/auditor/trail'; path: '/auditor/trail'; fullPath: '/auditor/trail'; preLoaderRoute: typeof AuditorTrailRouteImport; parentRoute: typeof rootRouteImport }
    '/auditor/flags': { id: '/auditor/flags'; path: '/auditor/flags'; fullPath: '/auditor/flags'; preLoaderRoute: typeof AuditorFlagsRouteImport; parentRoute: typeof rootRouteImport }
    '/auditor/irregularities': { id: '/auditor/irregularities'; path: '/auditor/irregularities'; fullPath: '/auditor/irregularities'; preLoaderRoute: typeof AuditorIrregularitiesRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/signup': { id: '/auth/signup'; path: '/auth/signup'; fullPath: '/auth/signup'; preLoaderRoute: typeof AuthSignupRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/login': { id: '/auth/login'; path: '/auth/login'; fullPath: '/auth/login'; preLoaderRoute: typeof AuthLoginRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthLoginRoute,
  AuthSignupRoute,
  AuditorRoute,
  AuditorFlagsRoute,
  AuditorIrregularitiesRoute,
  AuditorTrailRoute,
  BidsRoute,
  ClientRoute,
  ClientGate2Route,
  ClientPaymentsRoute,
  ClientProjectsRoute,
  ClientTendersRoute,
  ComplianceRoute,
  ConsultantRoute,
  ContractorRoute,
  ContractorBidsRoute,
  ContractorPaymentsRoute,
  ContractorProfileRoute,
  ContractorProjectsRoute,
  ContractorTendersRoute,
  DemoRoute,
  EvaluationRoute,
  LandingRoute,
  OrgRoute,
  PaymentsRoute,
  ProfessionalRoute,
  ProfileRoute,
  ProjectsRoute,
  PscRoute,
  ReportsRoute,
  SupplierRoute,
  TendersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
