/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as IndexRouteImport } from './routes/index'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bids': typeof BidsRoute
  '/compliance': typeof ComplianceRoute
  '/demo': typeof DemoRoute
  '/evaluation': typeof EvaluationRoute
  '/landing': typeof LandingRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/tenders': typeof TendersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bids': typeof BidsRoute
  '/compliance': typeof ComplianceRoute
  '/demo': typeof DemoRoute
  '/evaluation': typeof EvaluationRoute
  '/landing': typeof LandingRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/tenders': typeof TendersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bids': typeof BidsRoute
  '/compliance': typeof ComplianceRoute
  '/demo': typeof DemoRoute
  '/evaluation': typeof EvaluationRoute
  '/landing': typeof LandingRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/tenders': typeof TendersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bids'
    | '/compliance'
    | '/demo'
    | '/evaluation'
    | '/landing'
    | '/payments'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/tenders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bids'
    | '/compliance'
    | '/demo'
    | '/evaluation'
    | '/landing'
    | '/payments'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/tenders'
  id:
    | '__root__'
    | '/'
    | '/bids'
    | '/compliance'
    | '/demo'
    | '/evaluation'
    | '/landing'
    | '/payments'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/tenders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BidsRoute: typeof BidsRoute
  ComplianceRoute: typeof ComplianceRoute
  DemoRoute: typeof DemoRoute
  EvaluationRoute: typeof EvaluationRoute
  LandingRoute: typeof LandingRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  TendersRoute: typeof TendersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BidsRoute: BidsRoute,
  ComplianceRoute: ComplianceRoute,
  DemoRoute: DemoRoute,
  EvaluationRoute: EvaluationRoute,
  LandingRoute: LandingRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  TendersRoute: TendersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
